/* Automatically generated by './build/bin/build-entry.js' */

import DefaultLayout from '../packages/default-layout/index.js';
import oAxiosInterceptor from '../shared/utils/axios/axios.js';
import { Startup } from '../shared/utils/axios/startup.js';
import mStore from '../shared/utils/store/index.js';
import Http from '../shared/utils/http/index.js';
import Convert from '../shared/utils/convert/index.js';
import Cookie from '../shared/utils/cookie/index.js';
import ElementUI from 'element-ui';
import i18n from '../shared/locale/index.js';
import '../packages/icons/components';
import SvgIcon from 'vue-svgicon';
import Router from 'vue-router';

const components = [
  DefaultLayout
];

const install = function(Vue) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(ElementUI, {
    size: mStore.state.App.size,
    i18n: (key, value) => i18n.t(key, value)
  })

  Vue.use(SvgIcon, {
    tagName: 'svg-icon',
    defaultWidth: '1em',
    defaultHeight: '1em'
  });

  Vue.use(Router);

  Vue.prototype.$convert = Convert;
  Vue.prototype.$http = Http;
  Vue.prototype.$cookie = Cookie;
  Vue.prototype.$mStore = mStore;

  oAxiosInterceptor.init();

  Startup.bootstrap();
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.3',
  install,
  Http,
  Convert,
  Cookie,
  mStore,
  i18n,
  DefaultLayout
};
