/* Automatically generated by './build/bin/build-entry.js' */

import Card from '../packages/card/index.js';
import Convert from '../packages/convert/index.js';
import Http from '../packages/http/index.js';
import oAxiosInterceptor from '../shared/utils/axios/axios.js';
import { Startup } from '../shared/utils/axios/startup.js';

const components = [
  Card,
  Convert,
  Http
];

const install = function(Vue) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$convert = Convert;
  Vue.prototype.$http = Http;

  oAxiosInterceptor.init();

  Startup.bootstrap();
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  Card,
  Convert,
  Http
};
